---
- name: 'Fetch the kubeconfig file and replace 127.0.0.1 with the actual IP'
  hosts: 'all'
  gather_facts: true
  become: true

  roles:
    - name: 'johanneskastl.fetch_and_modify_a_kubeconfig_file'
      local_file_name: 'microk8s-kubeconfig'
      remote_file_path: '/var/snap/microk8s/current/credentials/client.config'
      actual_IP_to_use: "{{ external_ip | default(hostvars[inventory_hostname]['ansible_default_ipv4']['address']) }}"
